import AppKit

/// Translates between the system pasteboard and `ClipContent`.
public struct PasteboardReader {
    public init() {}

    private static let concealedMarkers: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    /// Read the current contents. Returns nil for empty/unsupported pasteboards.
    public func read(from pb: NSPasteboard) -> ClipContent? {
        let types = Set(pb.types ?? [])
        let isConcealed = !types.isDisjoint(with: Self.concealedMarkers)

        if let s = pb.string(forType: .string), !s.isEmpty {
            return isConcealed ? .concealed(text: s) : .text(s)
        }

        if let data = pb.data(forType: .png) ?? pb.data(forType: .tiff),
           let rep = NSBitmapImageRep(data: data) {
            let png = rep.representation(using: .png, properties: [:]) ?? data
            return .image(data: png, width: rep.pixelsWide, height: rep.pixelsHigh)
        }

        return nil
    }

    /// Write content back to the pasteboard so it becomes the active clipboard value.
    public func write(_ content: ClipContent, to pb: NSPasteboard) {
        pb.clearContents()
        switch content {
        case .text(let s):
            pb.setString(s, forType: .string)
        case .concealed(let s):
            pb.setString(s, forType: .string)
            // Re-tag so re-capture stays masked instead of surfacing plaintext.
            pb.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"))
        case .image(let data, _, _):
            pb.setData(data, forType: .png)
        }
    }
}
